---

- name: Ensure EUGridPMA apt key is installed (Debian)
  apt_key: 
    url: "{{ egi_igtf_repo_key_url }}"
    state: present 
  become: true

- name: Ensure EGI Trust Anchor repository is included (Debian)
  apt_repository: 
    repo: "deb {{ egi_igtf_repo_url }} egi-igtf {{ egi_igtf_components }}" 
    state: present 
  become: true

- name: Update package cache (Debian)
  apt: update_cache=yes cache_valid_time=86400
  become: yes

- name: Ensure latest versions of EGI Trust Anchors are installed (Debian)
  apt: pkg={{ item }} state=latest
  with_items:
    - ca-policy-egi-core
  become: true
